run-dist:
	./build/install/app/bin/app src/test/resources/fixtures/file1.json src/test/resources/fixtures/file2.json

run-dist-help:
	./build/install/app/bin/app -h

run-dist-version:
	./build/install/app/bin/app -V


.PHONY: build